services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://localhost:27017/admin",
          "--eval",
          "db.runCommand({ ping: 1 }).ok",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mongo_data:/data/db

  mongo-init:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    command: >
      bash -lc "mongosh mongodb://mongo:27017/admin --eval
      'try { rs.status() } catch (e) { rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"mongo:27017\"}]}) }' "

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  doc-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: doc-service
    env_file: .env
    ports: ["3000:3000"]
    depends_on:
      mongo-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    env_file: .env
    depends_on:
      mongo-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

volumes:
  mongo_data:
